nav:
  - Home: index.md
  - CLI Usage:
    - Basic Usage: cli/basic.md
    - Human-friendly IDs: cli/hid.md
    - Passwords: cli/pwd.md
    - UUIDs: cli/uuid.md
  - SDK Usage:
    - Basic Abstractions: sdk/basic.md
    - Human-friendly IDs: sdk/hid.md
    - Passwords: sdk/pwd.md
    - UUIDs: sdk/uuid.md

site_name: nohi
site_description: Fast command-line tool and library for generation human ids, uuids and passwords.

theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - instant

repo_name: unitto/nohi
repo_url: https://gitlab.com/unitto/nohi

google_analytics:
  - UA-86730462-2
  - auto

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/unitto/
    - icon: fontawesome/brands/gitlab
      link: https://github.com/unitto
    - icon: fontawesome/brands/github
      link: https://github.com/unitto1
